/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /root/catkin_ws/src/openreroc_gyrosensor/msg/gyro_sensor.msg
 *
 */


#ifndef OPENREROC_GYROSENSOR_MESSAGE_GYRO_SENSOR_H
#define OPENREROC_GYROSENSOR_MESSAGE_GYRO_SENSOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace openreroc_gyrosensor
{
template <class ContainerAllocator>
struct gyro_sensor_
{
  typedef gyro_sensor_<ContainerAllocator> Type;

  gyro_sensor_()
    : real_gx(0.0)
    , real_gy(0.0)
    , real_gz(0.0)  {
    }
  gyro_sensor_(const ContainerAllocator& _alloc)
    : real_gx(0.0)
    , real_gy(0.0)
    , real_gz(0.0)  {
    }



   typedef float _real_gx_type;
  _real_gx_type real_gx;

   typedef float _real_gy_type;
  _real_gy_type real_gy;

   typedef float _real_gz_type;
  _real_gz_type real_gz;




  typedef boost::shared_ptr< ::openreroc_gyrosensor::gyro_sensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::openreroc_gyrosensor::gyro_sensor_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct gyro_sensor_

typedef ::openreroc_gyrosensor::gyro_sensor_<std::allocator<void> > gyro_sensor;

typedef boost::shared_ptr< ::openreroc_gyrosensor::gyro_sensor > gyro_sensorPtr;
typedef boost::shared_ptr< ::openreroc_gyrosensor::gyro_sensor const> gyro_sensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::openreroc_gyrosensor::gyro_sensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::openreroc_gyrosensor::gyro_sensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace openreroc_gyrosensor

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'openreroc_gyrosensor': ['/root/catkin_ws/src/openreroc_gyrosensor/msg'], 'std_msgs': ['/opt/ros/groovy/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::openreroc_gyrosensor::gyro_sensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::openreroc_gyrosensor::gyro_sensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openreroc_gyrosensor::gyro_sensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::openreroc_gyrosensor::gyro_sensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openreroc_gyrosensor::gyro_sensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::openreroc_gyrosensor::gyro_sensor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::openreroc_gyrosensor::gyro_sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fb1d8484543516400f384b302e2d5d7f";
  }

  static const char* value(const ::openreroc_gyrosensor::gyro_sensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfb1d848454351640ULL;
  static const uint64_t static_value2 = 0x0f384b302e2d5d7fULL;
};

template<class ContainerAllocator>
struct DataType< ::openreroc_gyrosensor::gyro_sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "openreroc_gyrosensor/gyro_sensor";
  }

  static const char* value(const ::openreroc_gyrosensor::gyro_sensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::openreroc_gyrosensor::gyro_sensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 real_gx\n\
float32 real_gy\n\
float32 real_gz\n\
\n\
";
  }

  static const char* value(const ::openreroc_gyrosensor::gyro_sensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::openreroc_gyrosensor::gyro_sensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.real_gx);
      stream.next(m.real_gy);
      stream.next(m.real_gz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct gyro_sensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::openreroc_gyrosensor::gyro_sensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::openreroc_gyrosensor::gyro_sensor_<ContainerAllocator>& v)
  {
    s << indent << "real_gx: ";
    Printer<float>::stream(s, indent + "  ", v.real_gx);
    s << indent << "real_gy: ";
    Printer<float>::stream(s, indent + "  ", v.real_gy);
    s << indent << "real_gz: ";
    Printer<float>::stream(s, indent + "  ", v.real_gz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // OPENREROC_GYROSENSOR_MESSAGE_GYRO_SENSOR_H
